### PR TITLE
Fix 500 error

### PR DESCRIPTION
**Pull request by JamesNock**
Fixes error when trying to create a new entry in CraftCMS v4.4.16

### CODE REVIEW

**Comment by JamesNock** [comment]
@lindseydiloreto hey, is there any chance of getting this merged at all? 🙏

**Comment by lindseydiloreto** [comment]
Hi @JamesNock, happy Monday! Still getting caught up, we just returned from an international trip.

Thanks for submitting this fix, let me take a look into it today. 👍

**Comment by lindseydiloreto** [comment]
Done, this has been released in [v2.3.3](https://github.com/doublesecretagency/craft-starratings/releases/tag/2.3.3).

Thanks again @JamesNock! 🍺

**Comment by JamesNock** [comment]
Thank you 😀

**Pull request merged**
